"""alter_client_to_id_client_and_client_rel_to_client

Revision ID: 8b28109f5577
Revises: 8c54bf28f53b
Create Date: 2025-05-23 14:37:07.196684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b28109f5577'
down_revision: Union[str, None] = '8c54bf28f53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('id_client', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('order_client_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'client', ['id_client'], ['id_client'])
    op.drop_column('order', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_client_fkey'), 'order', 'client', ['client'], ['id_client'])
    op.drop_column('order', 'id_client')
    # ### end Alembic commands ###
