"""order table

Revision ID: 8c54bf28f53b
Revises: 25dd5cc849a5
Create Date: 2025-05-23 14:24:01.698296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c54bf28f53b'
down_revision: Union[str, None] = '25dd5cc849a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['client.id_client'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_index(op.f('ix_order_id_order'), 'order', ['id_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_id_order'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
