"""orderitem

Revision ID: a7339009c34e
Revises: 21e14833ee97
Create Date: 2025-05-23 14:46:35.067980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7339009c34e'
down_revision: Union[str, None] = '21e14833ee97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bar_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('valid_date', sa.DateTime(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('bar_code')
    )
    op.create_index(op.f('ix_product_id_product'), 'product', ['id_product'], unique=False)
    op.create_table('orderitem',
    sa.Column('id_orderitem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['order.id_order'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_orderitem')
    )
    op.create_index(op.f('ix_orderitem_id_orderitem'), 'orderitem', ['id_orderitem'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_id_orderitem'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_product_id_product'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
